// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0HPmgQL5rS1oquoxo85xztTyEjZ69dvo',
    appId: '1:709834819237:web:b6946a0c92151209baef4c',
    messagingSenderId: '709834819237',
    projectId: 'kitahack-setiau',
    authDomain: 'kitahack-setiau.firebaseapp.com',
    storageBucket: 'kitahack-setiau.firebasestorage.app',
    measurementId: 'G-B2EMB9N4M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPKNihzDePEDMV2RC-9Agb1Se7-Cn2u2o',
    appId: '1:709834819237:android:ac6f2664dd096e82baef4c',
    messagingSenderId: '709834819237',
    projectId: 'kitahack-setiau',
    storageBucket: 'kitahack-setiau.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWGuDqQOeBDFURMy-d-Oj9GKG_M4paAYM',
    appId: '1:709834819237:ios:e1bab93b65a75f84baef4c',
    messagingSenderId: '709834819237',
    projectId: 'kitahack-setiau',
    storageBucket: 'kitahack-setiau.firebasestorage.app',
    androidClientId: '709834819237-70odcahtniv3prj2f5fvj9q231cg06qp.apps.googleusercontent.com',
    iosClientId: '709834819237-c7fj9vr63qo5olf8icivethk33q2mdcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitahackSetiau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWGuDqQOeBDFURMy-d-Oj9GKG_M4paAYM',
    appId: '1:709834819237:ios:e1bab93b65a75f84baef4c',
    messagingSenderId: '709834819237',
    projectId: 'kitahack-setiau',
    storageBucket: 'kitahack-setiau.firebasestorage.app',
    androidClientId: '709834819237-70odcahtniv3prj2f5fvj9q231cg06qp.apps.googleusercontent.com',
    iosClientId: '709834819237-c7fj9vr63qo5olf8icivethk33q2mdcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitahackSetiau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0HPmgQL5rS1oquoxo85xztTyEjZ69dvo',
    appId: '1:709834819237:web:cc35941b6c2d4624baef4c',
    messagingSenderId: '709834819237',
    projectId: 'kitahack-setiau',
    authDomain: 'kitahack-setiau.firebaseapp.com',
    storageBucket: 'kitahack-setiau.firebasestorage.app',
    measurementId: 'G-CF2QDP3YLN',
  );

}