import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file was auto-generated by the CLI

void main() async {
  // 1. Ensure Flutter is ready before calling native code
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Wake up Firebase using your specific project keys
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'KitaHack App',
      home: Scaffold(
        appBar: AppBar(title: const Text('KitaHack 2026')),
        body: const Center(child: Text('Firebase is officially connected! 🚀')),
      ),
    );
  }
}
